name: build

on:
  workflow_call:
      helmEventTargetRepository:
        description: 'Target repository'
        default: ''
        required: false
        type: string

jobs:
  codeql:
    uses: onecx/ci-quarkus/.github/workflows/quarkus-codeql.yml@v1
    secrets: inherit
  quarkus:
    uses: onecx/ci-quarkus/.github/workflows/quarkus-build.yml@v1
    secrets: inherit
    with:
      push: true
  sonar:
    uses: onecx/ci-quarkus/.github/workflows/quarkus-sonar.yml@v1
    needs: quarkus
    secrets: inherit
  helm:
    uses: onecx/ci-common/.github/workflows/helm-build.yml@v1
    needs: quarkus
    secrets: inherit
    with:
      push: true
  helm-event:
    if: ${{ inputs.helmEventTargetRepository != '' }}
    uses: onecx/ci-common/.github/workflows/helm-update-event.yml@v1
    needs: helm
    secrets: inherit
    with:
      targetRepository: ${{ inputs.helmEventTargetRepository }}
