name: branch

on:
  workflow_call:
    inputs:
      native:
        description: 'Build native image'
        default: false
        required: false
        type: boolean
jobs:
  code-ql:
    uses: onecx/ci-quarkus/.github/workflows/quarkus-codeql.yml@v1
    secrets: inherit
  quarkus:
    uses: onecx/ci-quarkus/.github/workflows/quarkus-build.yml@v1
    secrets: inherit
    with:
      platform: ''
  liquibase:
    uses: onecx/ci-quarkus/.github/workflows/quarkus-liquibase.yml@v1
    secrets: inherit
  native:
    if: ${{ inputs.native }}
    uses: onecx/ci-quarkus/.github/workflows/quarkus-build-native.yml@v1
    secrets: inherit
    needs: [quarkus, liquibase]
    with:
      platform: ''
      args: '-Ob' # enable quick build mode
  helm:
    if: |
      !cancelled()
      && needs.quarkus.result == 'success'
      && needs.liquibase.result == 'success'
      && ( !inputs.native || needs.native.result == 'success')  
    uses: onecx/ci-common/.github/workflows/helm-build.yml@v1
    needs: [quarkus, native, liquibase]
    secrets: inherit