name: build

on:
  workflow_call:
    inputs:
      native:
        description: 'Build native image'
        default: false
        required: false
        type: boolean
      helmEventTargetRepository:
        description: 'Target repository'
        default: ''
        required: false
        type: string

jobs:
  codeql:
    uses: onecx/ci-quarkus/.github/workflows/quarkus-codeql.yml@f1
    secrets: inherit
  liquibase:
    uses: onecx/ci-quarkus/.github/workflows/quarkus-liquibase.yml@f1
    secrets: inherit    
  quarkus:
    uses: onecx/ci-quarkus/.github/workflows/quarkus-build.yml@f1
    secrets: inherit
    with:
      push: true
  sonar:
    uses: onecx/ci-quarkus/.github/workflows/quarkus-sonar.yml@f1
    needs: [quarkus]
    secrets: inherit
  native:
    if: ${{ inputs.native }}
    uses: onecx/ci-quarkus/.github/workflows/quarkus-build-native.yml@f1
    secrets: inherit
    needs: [quarkus]
    with:
      push: true    
  helm:
    uses: onecx/ci-common/.github/workflows/helm-build.yml@v1
    needs: [sonar, native, liquibase]
    secrets: inherit
    with:
      push: true
  helm-event:
    if: ${{ inputs.helmEventTargetRepository != '' }}
    uses: onecx/ci-product/.github/workflows/helm-send-event.yml@v1
    needs: helm
    secrets: inherit
    with:
      targetRepository: ${{ inputs.helmEventTargetRepository }}
