name: build

on:
  workflow_call:
    inputs:
      helmEventTargetRepository:
        description: 'Target repository'
        default: ''
        required: false
        type: string

jobs:
  codeql:
    uses: onecx/ci-quarkus/.github/workflows/quarkus-codeql.yml@v11
    secrets: inherit
  liquibase:
    uses: onecx/ci-quarkus/.github/workflows/quarkus-liquibase.yml@v11
    secrets: inherit    
  quarkus:
    uses: onecx/ci-quarkus/.github/workflows/quarkus-build.yml@v11
    secrets: inherit
    with:
     push: true      
  sonar:
    uses: onecx/ci-quarkus/.github/workflows/quarkus-sonar.yml@v11
    needs: [quarkus]
    secrets: inherit
  helm:
    uses: onecx/ci-common/.github/workflows/helm-build.yml@v11
    needs: [quarkus, liquibase]
    secrets: inherit
    with:
      push: true
  helm-event:
    if: ${{ inputs.helmEventTargetRepository != '' }}
    uses: onecx/ci-product/.github/workflows/helm-send-event.yml@v11
    needs: helm
    secrets: inherit
    with:
      targetRepository: ${{ inputs.helmEventTargetRepository }}
