name: quarkus-trivy

on:
    workflow_call:

jobs:
  quarkus-trivy:
    uses: onecx/ci-common/.github/workflows/docker-trivy-scan.yml@v2test
    secrets: inherit
    with:
      artifact: 'quarkus-version'
      artifactPath: 'quarkus-version.txt'
  quarkus-native-trivy:
    uses: onecx/ci-common/.github/workflows/docker-trivy-scan.yml@v2test
    secrets: inherit
    with:
      artifact: 'quarkus-version-native'
      artifactPath: 'quarkus-version-native.txt'
