name: sonar

on:
  workflow_call:
    inputs:
      jdk:
        description: 'JDK version'
        default: '17'
        required: false
        type: string 
      artifact:
        description: 'Name of the artifact for the build'
        default: 'package'
        required: false
        type: string   
      artifactPath:
        description: 'Artifact path'
        default: 'target'
        required: false
        type: string

jobs:
  sonar:
    name: sonar qa
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      # set up java and maven cache
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: ${{ inputs.jdk }}
          cache: 'maven'
      - uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar          
      - uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact }}
          path: ${{ inputs.artifactPath }}
      - name: Sonar publish analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  
          SONAR_URL: 'https://sonarcloud.io'      
        run: |
          SONAR_KEY="${GITHUB_REPOSITORY//\//_}"
          mvn -ntp -B -e org.sonarsource.scanner.maven:sonar-maven-plugin:3.9.1.2184:sonar -Dsonar.token=${{ secrets.SONAR_TOKEN }} -Dsonar.projectKey=$SONAR_KEY -Dsonar.organization=${{ github.repository_owner }} -Dsonar.host.url=$SONAR_URL -Dsonar.coverage.jacoco.xmlReportPaths=target/jacoco-report/jacoco.xml
        