name: quarkus

on:
  workflow_call:
    inputs:
      jdk:
        description: 'JDK version'
        default: '17'
        required: false
        type: string    
      native:
        description: 'Quarkus native build true/false'
        default: false
        required: false
        type: string
jobs:
  maven:
    name: build and test
    runs-on: ubuntu-latest
    env:
      QUARKUS_CONTAINER_IMAGE_REGISTRY: 'ghcr.io'
      QUARKUS_CONTAINER_IMAGE_GROUP: ${{ github.repository_owner }}
      QUARKUS_CONTAINER_IMAGE_BUILD: 'true'
      QUARKUS_CONTAINER_IMAGE_PUSH: 'false'
      QUARKUS_CONTAINER_IMAGE_LABEL_SOURCE: ${{ github.repositoryUrl }}
      QUARKUS_CONTAINER_IMAGE_LABEL_SHA: ${{ github.sha }}
    steps:
    # checkout the project
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    # set up java and maven cache
    - uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: ${{ inputs.jdk }}'
        cache: 'maven'
    # login to github docker registry in the organization
    - uses: docker/login-action@v2
      with:
        registry: ${{ env.QUARKUS_CONTAINER_IMAGE_REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}      
    # build JVM version
    - name: Build jvm project, run tests and push docker image
      if: ${{ !inputs.native }}
      run: mvn -ntp -B -e clean impsort:check formatter:validate verify --file pom.xml
    # build NATIVE version  
    - name: Build native project, run tests and push docker image
      if: ${{ inputs.native }}
      run: mvn -ntp -B -e -Pnative clean impsort:check formatter:validate verify --file pom.xml
    # uplaod target for next jobs      
    - uses: actions/upload-artifact@v3
      with:
        name: package
        path: target
        retention-days: 1
        if-no-files-found: ignore
